### ISSUE TITLE
Images and other assets not working on deployed version. 

### ISSUE THREAD

**Issue by Hex4dec** [pranavinsight/myportfolio#2]
If you try to browse to [the deployed version of the website](https://pranavinsight.github.io/myportfolio/), it will fail to load assets (atleast on my side, i have uBlock Origin and Ungoogled Chromium).

This is most likely caused because the image paths are prefixed by `Images/`, but in the repository there is no such directory. This is an easy fix, and I can send a pull request for this.

**Comment by pranavinsight** [comment]
Sure! I can help you with that. Btw, i am from India so, i may message you a bit too late.
Thank you, that was so close!

**Comment by pranavinsight** [comment]
Thank you for informing me @Hex4dec ! I appreciate your error finding skills. All good. So, this issue is announced to be closed.
